Repository ComPWA/compwa.github.io, pull requests merged in 2024-09, with the labels that each got.

#291 FIX: typo and enhance Geogebra plots
  docs/report/033.ipynb
Labels: 🐛 Bug

#292 MAINT: autoupdate constraints and pre-commit config
  .constraints/py3.10.txt
  .constraints/py3.11.txt
  .constraints/py3.12.txt
  .constraints/py3.7.txt
  .constraints/py3.8.txt
  .constraints/py3.9.txt
  .cspell.json
  .envrc
  .gitattributes
  .gitignore
  .gitpod.yml
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  docs/conf.py
  docs/develop.md
  environment.yml
  pyproject.toml
  tox.ini
Labels: 🔨 Maintenance

#294 FIX: prevent TR-028 (PDG API) from running
  .cspell.json
  docs/conf.py
  docs/report/028.ipynb
Labels: 🔨 Maintenance

#270 DX: enforce `import`s to top by default
  .pre-commit-config.yaml
  docs/report/004.ipynb
  docs/report/014.ipynb
  docs/report/015.ipynb
  docs/report/017.ipynb
  docs/report/021.ipynb
  docs/report/026.ipynb
  docs/report/033.ipynb
  pyproject.toml
Labels: 🖱️ DX
